cmd: don't print full help/usage on error
When a command returns an error the usage string was always displayed.
While this may be useful on unexpected user input, it's disconcerting
when the error is internal to hubble (eg: socket connection lost).

Thus, disable displaying the full help message by default. This change
propagates to all subcommands.
On wrong user input, a short message is instead displayed instead.

Example:
    $ hubble observe -d
    Error: unknown shorthand flag: 'd' in -d
    unknown shorthand flag: 'd' in -d

Signed-off-by: Robin Hahling <robin.hahling@gw-computing.net>